joephpmysql_container:
  image: joephpmysql
  links:
    - joemysql_container:mysqlhost
  ports:
    - 80:80
  volumes:
    - ~/Projects/sources/php-mysql:/var/www/html 

joemysql_container:
  image: mysql:5.7.13
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: test_db
  volumes:
    - ~/.docker-volumes/joephpmysql/mysql/data:/var/lib/mysql
