# Guide here:
# https://hub.docker.com/r/kyma/docker-nginx/

# Build from this repo's image
FROM kyma/docker-nginx

# Add src.
# (this line will do nothing in this case, cause I have nothing in this folder)
COPY . /var/www

CMD 'nginx'
